---
- name: Install web server
  hosts: web
  remote_user: user
  become: true
  vars_files:
    - vars.yml
  vars:
    webserver_message: "I'm running"
    ansible_ssh_private_key_file: "{{ key }}"
  tasks:
    - name: Install epel-repo
      yum:
        name: epel-release
        state: latest

    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      template:
        src: /home/burmistrov/templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
