---
- name: Playbook1
  hosts: all
  tasks:
    - name: Download Apache Kafka
      get_url:
        url: https://downloads.apache.org/kafka/3.3.1/kafka-3.3.1-src.tgz
        dest: /tmp/kafka-3.3.1-src.tgz
        mode: 0755

    - name: Create folder for extract Kafka
      file: "path=/home/burmistrov/kafka-3.3.1 state=directory"

    - name: Extract archive
      unarchive:
        src: /tmp/kafka-3.3.1-src.tgz
        dest: /home/burmistrov/kafka-3.3.1
        extra_opts: [--strip-components=1]
        remote_src: yes