---
- name: Playbook4
  hosts: all
  become: true

  vars:
    - greeting: "Hello, have a good day, "
    - admin_name: Oleg

  tasks:
      - name: Change motd
        shell: echo "{{ greeting  }} {{ admin_name  }}" > /etc/motd

      - name: Add string to motd
        shell: echo "{{ ansible_facts['fqdn']  }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" >> /etc/motd
